### PR TITLE
Don't allow subscription with existing user key

### LINKED ISSUE #164: Reject subscriptions for existing users
## Bug description
Streams `Author's` should not process subscription requests that use the same `Identifier` as an existing user in the channel (especially not their own).

## Steps To reproduce the bug
1. Create an `Author` and send an `Announce` message 
2. Create a `Subscriber` using the same seed as `Author`
3. Send `Subscribe` message to `Author` and receive it

## Expected behaviour
`Subscriber` should not be able to process through step 3. `Author` should fail to receive message because the `Subscriber` has a public key that matches an existing user (`Author`) 

## Actual behaviour
`Subscriber` is being processed and overwriting the `Author` state in store as a result. 

Relates to #159

### PR DESCRIPTION
**Pull request by DyrellC**
# Description of change
Stop `Author` from accepting `Subscribe` messages that are sent from a user with an already registered `Identifier`. Existing user states should not be overwritten. 

Fixes #164 

## Type of change
- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested
- Existing examples and binding examples continue to pass (including `streams-examples` repo tests)
- Ran example from #159 and received an error for trying to subscribe with the same seed as author
- Modified example form #159 removing subscription process completes successfully

## Change checklist
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by arnauorriols** [comment]
Also fixes #159

File: iota-streams-app-channels/src/api/user.rs [hunk 1]
```diff
@@ -416,8 +416,12 @@ where
...
     pub fn insert_subscriber(&mut self, pk: ed25519::PublicKey) -> Result<()> {
         let ref_link = self.appinst.as_ref().unwrap().rel().clone();
-        self.key_store
-            .insert_cursor(pk.into(), Cursor::new_at(ref_link, 0, SEQ_MESSAGE_NUM))
+        match !self.key_store.contains(&pk.into()) {
+            true => self
+                .key_store
+                .insert_cursor(pk.into(), Cursor::new_at(ref_link, 0, SEQ_MESSAGE_NUM)),
+            false => err!(UserAlreadyRegistered(hex::encode(pk.as_bytes()))),
+        }
```
Comment (arnauorriols) [inline iota-streams-app-channels/src/api/user.rs:424]: We should probably guard against using this without registering first, and get rid of that `unwrap`. Here's my suggestion:
```suggestion
        match (!self.key_store.contains(&pk.into()), &self.appinst) {
            (_, None) => err!(UserNotRegistered),
            (true, Some(ref_link)) => self
                .key_store
                .insert_cursor(pk.into(), Cursor::new_at(ref_link.rel().clone(), 0, SEQ_MESSAGE_NUM)),
            (false, Some(_)) => err!(UserAlreadyRegistered(hex::encode(pk.as_bytes()))),
        }
```

**Review by arnauorriols — APPROVED** [review]
I've left a message suggesting an improvement, but it's not a blocker.

File: iota-streams-app-channels/src/api/user.rs (hunk 1 above)
Comment (DyrellC) [reply iota-streams-app-channels/src/api/user.rs:424]: I like it, any excuse to remove an unwrap i'm usually on board with.

File: iota-streams-core/src/errors/error_messages.rs [hunk 2]
```diff
@@ -136,7 +136,7 @@ pub enum Errors {
     //////////
     /// Cannot create a channel, user is already registered to channel {0}
     ChannelCreationFailure(String),
-    /// Cannot unwrap announcement message, already registered to channel {0}
+    /// Cannot unwrap message, user already registered to channel {0}
```
Comment (kwek20) [inline iota-streams-core/src/errors/error_messages.rs:139]: This is technically incorrect! Were not doing any message unwrapping here!

Lets change to: `Cannot register new user; user is already registered to channel {0}`

Comment (DyrellC) [reply iota-streams-core/src/errors/error_messages.rs:139]: Both uses are done during handle/unwrap instances, but I still think that's a good change for the message anyways, i'll update it

Comment (DyrellC) [reply iota-streams-core/src/errors/error_messages.rs:139]: I'm actually going to add the identifier as well, there are 2 places to use it and they're printing separate things, one prints the `appinst` and the other the `identifier`, so i'm going to have both print in the message to make it more concise.

**Review by kwek20 — APPROVED** [review]
